spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/pegasusdb}
    username: ${DATABASE_USERNAME:pegasus}
    password: ${DATABASE_PASSWORD:1234}

  sql:
    init:
      mode: ALWAYS

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    properties:
      hibernate:
        format_sql: true